import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TopHeader from "@/components/TopHeader/TopHeader";
import AppBar from "@/components/AppBar/AppBar";

const segoeui = localFont({
  src: "./fonts/segoeuii.woff",
  variable: "--font-segoe-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dashboard Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${segoeui.variable} antialiased`}
      >
        <TopHeader/>
      <div className="w-full h-screen sm:h-[calc(100vh-48px)] flex flex-row">
        <AppBar/>
        {children}
      </div>
      </body>
    </html>
  );
}
